import { Injectable, UnauthorizedException, NotFoundException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { UsersService } from '../users/users.service.js';
import * as bcrypt from 'bcrypt';
import { LoginDto } from './dto/login.dto.js';
import { ForgotPasswordDto } from './dto/forget-password.dto';

import { RegisterDto } from './dto/register.dto.js';

@Injectable()
export class AuthService {
  constructor(
    private usersService: UsersService,
    private jwtService: JwtService,
  ) { }

  // ✨ NEW: User Registration (Signup)
  async register(registerDto: RegisterDto) {
    try {
      const { email, password, name } = registerDto;

      // 1. Check if user already exists
      const existingUser = await this.usersService.findByEmail(email);
      if (existingUser) {
        throw new UnauthorizedException('Email already in use');
      }

      // 2. Hash the password
      const hashedPassword = await bcrypt.hash(password, 10);

      // 3. Create the user (slug is auto-generated by the schema!)
      const user = await this.usersService.create({
        name,
        email,
        password: hashedPassword,
      });

      return {
        message: 'User registered successfully!',
        user: {
          id: user._id,
          name: user.name,
          email: user.email,
          slug: user.slug,
        },
      };
    } catch (err : any) {
      console.error("REGISTER ERROR =>", err);
      throw new Error(`DEBUG: ${err.message}`);
    }
  }

  async login(loginDto: LoginDto) {
    const { email, password } = loginDto;

    const user = await this.usersService.findByEmailWithPassword(email);
    if (!user) {
      throw new UnauthorizedException('Invalid email or password');
    }

    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      throw new UnauthorizedException('Invalid email or password');
    }

    const payload = { email: user.email, sub: user._id };
    const token = this.jwtService.sign(payload);

    return {
      message: 'Login successful',
      access_token: token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        slug: user.slug,
      },
    };
  }

  async forgotPassword(forgotPasswordDto: ForgotPasswordDto) {
    const { email, newPassword } = forgotPasswordDto;

    const user = await this.usersService.findByEmailWithPassword(email);
    if (!user) {
      throw new NotFoundException('No account found with this email');
    }

    const hashedPassword = await bcrypt.hash(newPassword, 10);
    user.password = hashedPassword;
    await user.save();

    return { message: 'Password updated successfully' };
  }
}